---

- name: Pull image
  command: docker compose pull
  args:
    chdir: "{{ shadowsocks_service_dir }}"
  when: not ansible_check_mode

- name: Up image
  command: docker compose up -d
  args:
    chdir: "{{ shadowsocks_service_dir }}"
  when: not ansible_check_mode

- name: Restart shadowsocks
  service:
    name: docker-compose@shadowsocks
    state: restarted
  when: not ansible_check_mode
