---

- name: Pull image
  command: docker compose pull
  args:
    chdir: "{{ wireguard_service_dir }}"
  when: not ansible_check_mode

- name: Up image
  command: docker compose up -d
  args:
    chdir: "{{ wireguard_service_dir }}"
  when: not ansible_check_mode

- name: Restart wireguard
  service:
    name: docker-compose@wireguard
    state: restarted
  when: not ansible_check_mode
