---

- name: Mkdir for resilio
  file:
    path: "{{ item }}"
    state: directory
    mode: "0o750"
  with_items:
    - "{{ resilio_service_dir }}"

- name: Resilio config directories
  file:
    state: directory
    mode: "0o755"
    path: "{{ resilio_service_dir }}/{{ item }}"
  loop:
    - "{{ resilio_data }}"
  tags:
    - config

- name: Copy dot.env file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: dot.env.j2
    dest: "{{ resilio_service_dir }}/.env"
    mode: "0o640"
  no_log: true
  notify:
    - Restart resilio

- name: Copy docker-compose file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: docker-compose.yml
    dest: "{{ resilio_service_dir }}"
    mode: "0o640"
  notify:
    - Pull image
    - Up image
    - Restart resilio
  tags:
    - docker_compose

- name: Start and enable resilio
  service:
    name: docker-compose@resilio
    state: started
    enabled: true
