---

- name: Mkdir for watchtower
  file:
    path: "{{ item }}"
    state: directory
    mode: "0o750"
  with_items:
    - "{{ watchtower_service_dir }}"

- name: Copy dot.env file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: dot.env.j2
    dest: "{{ watchtower_service_dir }}/.env"
    mode: "0o640"
  no_log: true
  notify:
    - Restart watchtower

- name: Copy docker-compose file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: docker-compose.yml
    dest: "{{ watchtower_service_dir }}"
    mode: "0o640"
  notify:
    - Pull image
    - Up image
    - Restart watchtower
  tags:
    - docker_compose

- name: Start and enable watchtower
  service:
    name: docker-compose@watchtower
    state: started
    enabled: true
