version: "3.3"
services:

  watchtower:
    image: ${WATCHTOWER_IMAGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always

networks:
  default:
    name: traefik-proxy
    external: true
