---

- name: Pull image
  command: docker compose pull
  args:
    chdir: "{{ watchtower_service_dir }}"
  when: not ansible_check_mode

- name: Up image
  command: docker compose up -d
  args:
    chdir: "{{ watchtower_service_dir }}"
  when: not ansible_check_mode

- name: Restart watchtower
  service:
    name: docker-compose@watchtower
    state: restarted
  when: not ansible_check_mode
