---

- name: Pull image
  command: docker compose pull
  args:
    chdir: "{{ nextcloud_service_dir }}"
  when: not ansible_check_mode

- name: Up image
  command: docker compose up -d
  args:
    chdir: "{{ nextcloud_service_dir }}"
  when: not ansible_check_mode

- name: Restart nextcloud
  service:
    name: docker-compose@nextcloud
    state: restarted
  when: not ansible_check_mode
