---

- name: Mkdir for brook
  file:
    path: "{{ item }}"
    state: directory
    mode: "0o750"
  with_items:
    - "{{ brook_service_dir }}"

- name: Copy dot.env file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: dot.env.j2
    dest: "{{ brook_service_dir }}/.env"
    mode: "0o640"
  no_log: true
  notify:
    - Restart brook

- name: Copy docker-compose file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: docker-compose.yml
    dest: "{{ brook_service_dir }}"
    mode: "0o640"
  notify:
    - Pull image
    - Up image
    - Restart brook
  tags:
    - docker_compose

- name: Start and enable brook
  service:
    name: docker-compose@brook
    state: started
    enabled: true
