---

- name: Mkdir for ipsec
  file:
    path: "{{ item }}"
    state: directory
    mode: "0o750"
  with_items:
    - "{{ ipsec_service_dir }}"

- name: Mkdir for ipsec config
  file:
    path: "{{ item }}"
    state: directory
    mode: "0o750"
  with_items:
    - "{{ ipsec_service_dir }}/ipsec"

- name: Copy dot.env file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: dot.env.j2
    dest: "{{ ipsec_service_dir }}/ipsec/vpn.env"
    mode: "0o640"
  no_log: true
  notify:
    - Restart ipsec

- name: Copy docker-compose file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: docker-compose.yml
    dest: "{{ ipsec_service_dir }}"
    mode: "0o640"
  notify:
    - Pull image
    - Up image
    - Restart ipsec
  tags:
    - docker_compose

- name: Start and enable ipsec
  service:
    name: docker-compose@ipsec
    state: started
    enabled: true
