---

- name: Mkdir for traefik
  file:
    path: "{{ item }}"
    state: directory
    mode: "0o750"
  with_items:
    - "{{ traefik_service_dir }}"

- name: Mkdir for traefik
  file:
    path: "{{ item }}"
    state: directory
    mode: "0o750"
  with_items:
    - "{{ traefik_service_dir }}"

- name: Traefik config directories
  file:
    state: directory
    mode: "0o755"
    path: "{{ traefik_service_dir }}/{{ item }}"
  loop:
    - "{{ traefik_logs }}"
    - "{{ traefik_conf }}"
  tags:
    - config


- name: Copy dot.env file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: traefik.yml
    dest: "{{ traefik_service_dir }}/conf/"
    mode: "0o640"
  no_log: true
  notify:
    - Restart traefik

- name: Copy docker-compose file
  ignore_errors: "{{ ansible_check_mode }}"
  template:
    src: docker-compose.yml
    dest: "{{ traefik_service_dir }}"
    mode: "0o640"
  notify:
    - Pull image
    - Up image
    - Restart traefik
  tags:
    - docker_compose

- name: Start and enable traefik
  service:
    name: docker-compose@traefik
    state: started
    enabled: true
