version: "3.3"
services:
  wireguard:
    image: ${WG_IMAGE}
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD=${WG_PASS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.middlewares=secHeaders@file"
      - "traefik.http.routers.wireguard.rule=Host(`${WG_HOST}`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.routers.wireguard.tls=true"
      - "traefik.http.routers.wireguard.tls.certresolver=LetsEncrypt"
      - "traefik.http.routers.wireguard.service=wireguard"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ${WG_DATA}:/etc/wireguard
    ports:
      - ${WG_PORT}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: always

networks:
  default:
    name: traefik-proxy
    external: true
